### ISSUE TITLE
Direct Reply-to

### ISSUE THREAD

**Issue by bararchy** [cloudamqp/amqp-client.cr#10]
Is there a way to use the following method? https://www.rabbitmq.com/direct-reply-to.html

**Comment by carlhoerberg** [comment]
yes, as outlined in the article: 

- Consume from the pseudo-queue amq.rabbitmq.reply-to in no-ack mode. There is no need to declare this "queue" first, although the client can do so if it wants.
- Set the reply-to property in their request message to amq.rabbitmq.reply-to.

There's nothing special that the client has to support.

**Comment by johanrhodin** [comment]
This will eventually be included as an example as we provide the RabbitMQ-tutorials for this client.

**Comment by bararchy** [comment]
Thanks @carlhoerberg , @johanrhodin.
