### ISSUE TITLE
Basic Server + AMQP Client

### ISSUE THREAD

**Issue by KCErb** [cloudamqp/amqp-client.cr#18]
Hi there, not sure if this is the best place for a "how do I" question. I apologize in advance if you have a forum for that that I missed.

I wanted to check my logic on combining the basic HTTP server in the [crystal docs](https://crystal-lang.org/api/0.35.1/HTTP/Server.html) with a basic AMQP server:
```crystal
require "http/server"
require "amqp-client"

server = HTTP::Server.new do |context|
  context.response.content_type = "text/plain"
  context.response.print "Hello world!"
end

spawn do
  AMQP::Client.start("amqp://guest:guest@localhost") do |connection|
    connection.channel do |ch|
      q = ch.queue("hello")
      puts " [*] Waiting for messages."
      q.subscribe(block: true) do |msg|
        puts " [x] Received #{msg.body_io.to_s}"
      end
    end
  end
end

address = server.bind_tcp 8080
puts "Listening on http://#{address}"
server.listen
```

The experience seems right (both servers are responsive), but I'm not sure if I should be using `block: true` in a fiber like this, or if it's intended to normally use `block: false` plus my own fiber handling like a loop that consumes and yields or something of that nature. Suggestions?

**Comment by carlhoerberg** [comment]
that looks very good!
