### ISSUE TITLE
RPC example

### ISSUE THREAD

**Issue by aabajyan** [cloudamqp/amqp-client.cr#25]
It would be great if there was an example of writing a remote procedure call with this library using Thread::Mutex and Thread::ConditionVariable. I attempted to do this, but I failed. So I used sleep instead, which works but I don't think is really the best way to do it.

My code so far: https://github.com/aabajyan/norminette.cr/blob/main/src/sender.cr
RPC on RabbitMQ: https://www.rabbitmq.com/tutorials/tutorial-six-ruby.html

**Comment by carlhoerberg** [comment]
Is your Sender the RPC server or the RPC client?

**Comment by carlhoerberg** [comment]
modified your sender to be a RPC client: https://gist.github.com/carlhoerberg/4fcd7af4817e9ebf6774d42c5c33df0a 

untested, but you get the idea, to use a correlation_id + `Channel` to get the responses

**Comment by aabajyan** [comment]
Hello, Thank you for your response!
It looks good to me!
