### ISSUE TITLE
Empty vhost when URL has trailing slash

### ISSUE THREAD

**Issue by jrester** [cloudamqp/amqp-client.cr#9]
When creating a new Client from a URL with a trailing slash like `amqp://localhost:5672/` the vhost is initialized with an empty string which results in a vhost not found error. 
The Problem might be that when checking the vhost it is never checked whether the path is just `/` as well as when using `URI.decode_www_form` the last character is omitted.

**Comment by carlhoerberg** [comment]
Thank you for reporting, fixed!
